### ISSUE TITLE
Division By Zero

### ISSUE THREAD

**Issue by FreeLikeGNU** [rr-/pq-cli#1]
- installed python3.7 and python3.7-venv package from ubuntu 18.04 repos
- created a python3.7 env
- activated the env
- installed pqcli per intructions
- python -V output is Python 3.7.1

- pqcli runs with main menu and character creation up to stats but selecting "Continue" causes error:

`pqcli 
Traceback (most recent call last):
  File "/home/francisco/py37env/bin/pqcli", line 11, in <module>
    load_entry_point('pqcli==1.0', 'console_scripts', 'pqcli')()
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/__main__.py", line 56, in main
    ui.run()
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/__init__.py", line 95, in run
    self._view.keypress(key)
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/views/menu_view.py", line 41, in keypress
    self.main_menu.keypress(key)
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/widgets/menu.py", line 66, in keypress
    self._choices[self._active_choice].callback()
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/event_handler.py", line 10, in __call__
    callback(*args, **kwargs)
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/__init__.py", line 175, in _switch_to_game_view
    self._switch_view(view)
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/__init__.py", line 180, in _switch_view
    self._view.start()
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/views/game_view/__init__.py", line 214, in start
    x=0,
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/views/game_view/quest_book_window.py", line 24, in __init__
    self.sync()
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/views/game_view/quest_book_window.py", line 44, in sync
    self._sync_quests()
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/views/game_view/quest_book_window.py", line 51, in _sync_quests
    self._list_box.select(-1)
  File "/home/francisco/py37env/lib/python3.7/site-packages/pqcli/ui/curses/widgets/list_box.py", line 41, in select
    idx %= len(self._items)
ZeroDivisionError: integer division or modulo by zero
`

**Comment by rr-** [comment]
Hah, sorry for your terrible experience.
It's now fixed on master: https://github.com/rr-/pq-cli/commit/82c8d2139574b3865a25260f6f5c7b67a7b8db48

**Comment by FreeLikeGNU** [comment]
thank you... I tried again with
`$ sudo apt install python3.7 python3-pip
$ python3.7 -m venv env
$ source py37env/bin/activate
$ python -V
$ pip3.7 install wheel
$ pip3.7 install pqcli`

that worked, but not sure if it had to do with your recent changes, thank you anyways!

**Comment by rr-** [comment]
Glad to hear that :)
