### ISSUE TITLE
I installed Python 3.8 and it won't work

### ISSUE THREAD

**Issue by aknight2015** [rr-/pq-cli#12]
I'm running windows 10. I installed Python 3.8 from the store. I went into command line and typed pip install --user pqcli, everything went fine. I typed pqcli and it says that "pqcli is not recobnized as an internal or external command, operable program or batch file."

How can I fix this?

**Comment by rr-** [comment]
Try python3.8 -m pqcli

**Comment by aknight2015** [comment]
I get this.

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Steve Rogers\pq-cli\pqcli\__main__.py", line 8, in <module>
    from pqcli.ui.curses import CursesUserInterface
  File "C:\Users\Steve Rogers\pq-cli\pqcli\ui\curses\__init__.py", line 2, in <module>
    import curses
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by rr-** [comment]
For some reason your python doesn't think you're running Windows; try installing also `pip install --user windows-curses`

**Comment by aknight2015** [comment]
Can't say I completely blame it. It's working now.

**Comment by aknight2015** [comment]
Can't say I completely blame it. It's working now.
