### ISSUE TITLE
This error occurs immediately after finalizing character creation, before anything pops up...:

### ISSUE THREAD

**Issue by DamekLeedt** [rr-/pq-cli#13]
`Traceback (most recent call last):
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\__main__.py", line 56, in main
    ui.run()
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\ui\curses\__init__.py", line 95, in run
    self._view.keypress(key)
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\ui\curses\views\create_character_view\choose_character_stats_view.py", line 58, in keypress
    self.on_confirm(self._stats)
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\ui\curses\event_handler.py", line 10, in __call__
    callback(*args, **kwargs)
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\ui\curses\__init__.py", line 145, in <lambda>
    view.on_confirm += lambda stats: self._create_character(
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\ui\curses\__init__.py", line 188, in _create_character
    self.roster.save()
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\roster.py", line 32, in save
    self.path.rename(old_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1358, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '$HOME\\.config\\pqcli\\save.dat' -> '$HOME\\.config\\pqcli\\save.dat.old'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\__main__.py", line 63, in <module>
    main()
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\__main__.py", line 59, in main
    roster.save()
  File "C:\Users\eyedp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pqcli\roster.py", line 32, in save
    self.path.rename(old_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1358, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '$HOME\\.config\\pqcli\\save.dat' -> '$HOME\\.config\\pqcli\\save.dat.old'`

Sorry for the dump! Big error.

**Comment by rr-** [comment]
Please try installing 1.0.2 @DamekLeedt which contains a bugfix for this particular scenario. I just released it on PyPI.

**Comment by DamekLeedt** [comment]
How do I do that? Newbie to shell and python stuff, here.

**Comment by rr-** [comment]
I don't know how you installed it in the first place but maybe `pip install --user --upgrade pqcli`?

**Comment by DamekLeedt** [comment]
It worked!! Thank you!

**Comment by rr-** [comment]
You're welcome :)
