### ISSUE TITLE
Not starting on a machine with python 3.10

### ISSUE THREAD

**Issue by vatonbero** [rr-/pq-cli#19]
Hi there,

I have tried installing from pip and downloading and yet I end up with the same message on my Fedora 35 box:

```
Traceback (most recent call last):
File "/home/gralavatarkoluk/.local/bin/pqcli", line 8, in <module>
sys.exit(main())
File "/home/gralavatarkoluk/.local/lib/python3.10/site-packages/pqcli/__main__.py", line 55, in main
ui = args.ui(roster, args)
File "/home/gralavatarkoluk/.local/lib/python3.10/site-packages/pqcli/ui/curses/__init__.py", line 49, in __init__
curses.curs_set(0)
_curses.error: curs_set() returned ERR
```

I have python 3.10. Can i do anything to start this program here? Thank you

**Comment by rr-** [comment]
Thanks for the bug report. Sadly I can't help you with debugging curses installation problem, but you could try running the game with `--basic`.

**Comment by vatonbero** [comment]
> Thanks for the bug report. Sadly I can't help you with debugging curses installation problem, but you could try running the game with `--basic`.

Oh, I thought this is game related and not a distro curses issue. It is fine, game works using `--basic`

I shall close this issue then!
