### ISSUE TITLE
getting "addnwstr() returned ERR" when the 'game' starts

### ISSUE THREAD

**Issue by RetroZelda** [rr-/pq-cli#23]
from latest github I get this error after I create, or continue with, a player:

`Traceback (most recent call last):
  File "/home/quester/pq-venv/bin/pqcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/__main__.py", line 88, in main
    ui.run()
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/__init__.py", line 100, in run
    self._view.keypress(key)
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/views/menu_view.py", line 40, in keypress
    self.main_menu.keypress(key)
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/widgets/menu.py", line 66, in keypress
    self._choices[self._active_choice].callback()
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/event_handler.py", line 10, in __call__
    callback(*args, **kwargs)
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/__init__.py", line 182, in _switch_to_game_view
    self._switch_view(view)
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/__init__.py", line 187, in _switch_view
    self._view.start()
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/views/game_view/__init__.py", line 197, in start
    self._plot_win = PlotWindow(
                     ^^^^^^^^^^^
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/views/game_view/plot_window.py", line 25, in __init__
    self.sync()
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/views/game_view/plot_window.py", line 46, in sync
    self._sync_position()
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/views/game_view/plot_window.py", line 69, in _sync_position
    self._render_progress_bar()
  File "/home/quester/pq-venv/lib/python3.11/site-packages/pqcli/ui/curses/views/game_view/progress_bar_window.py", line 68, in _render_progress_bar
    self._progress_bar_win.addnstr(
_curses.error: addnwstr() returned ERR`

**Comment by rr-** [comment]
I can't replicate it

**Comment by RetroZelda** [comment]
Hello, 
This user doesnt have sudo permissions and its only role is to run pq-cli and a https://tty-share.com/ instance so I can watch the progress when im bored. 

Things were working fine when I was on debian stable, but I recently moved the machine up to testing for an nvidia issue for an unrelated thing on the system.  So now the machine is:
- Debian Trixie, Kernel 6.6.13-amd64
- Shell: bash 5.2.21
- CPU: AMD Tyzen 7 5700x
- Python: 3.11.8

this is the results from freeze:
`pqcli @ file:///home/quester/pq-cli
urwid==2.1.2
urwid-readline==0.13
xdg==5.1.1`

This is a headless machine, so I start pq-cli with a systemd service into a screen.  In the service file I define `Environment="TERM=xterm-256color"` 

Because its a headless server I dont have x11 or wayland or any window manager so I typically connect to it via ssh, but the same occurs if I plug a monitor into the machine and login directly.  

and in screen I pass it this script used to start pq-cli:
`#!/bin/bash

python3 -m venv pq-venv
source pq-venv/bin/activate

git clone https://github.com/rr-/pq-cli.git
pip3 install ./pq-cli

export TERM=xterm-256color
pqcli --load-save 1

deactivate
`
In the log(and the output if I manually run it) I see the main menu printed once before the crash stack appears, but I can still run with --basic without any issues

**Comment by genewitch** [comment]
i have this same error/issue on Kali linux (rolling release but up to date), 
term: qterminal version: 1.4.0-1
$TERM xterm-256colors
Python 3.11.6

installed from pip and manually edited the mechanic.py random.seed(**now**) to **str(now)** 

If there's any way i can help track this i'll try, but i got it running on windows for now anyhow. Thanks!

**Comment by txtsd** [comment]
Does it run if you pass `--basic`?

**Comment by RetroZelda** [comment]
looking at it again I tried it on my daily machine that is also debian trixie and I get the same thing on every terminal emulator I tried.  

I did find a workaround for my specific desires by throwing this together https://github.com/RetroZelda/pqcli-stream
its generally using xterm from ubuntu in a docker container and it streams to twitch using ffmpeg instead of using tty-share.

**Comment by noUsernamesLef7** [comment]
I'm also running into this on an Arch based distro. The crash occurs when I hit F10 to continue at the character stat rolls screen. I'm using the latest commit. 803eba416e6f2ec36ea74269abcee3cd91c4c124

```
Python: 3.12.4

urwid==2.6.10
urwid_readline==0.14
xdg-base-dirs==6.0.1
```

```
Traceback (most recent call last):
  File "/usr/bin/pqcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/pqcli/__main__.py", line 88, in main
    ui.run()
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/__init__.py", line 100, in run
    self._view.keypress(key)
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/views/create_character_view/choose_character_stats_view.py", line 71, in keypress
    self.on_confirm(self._stats)
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/event_handler.py", line 10, in __call__
    callback(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/__init__.py", line 152, in <lambda>
    view.on_confirm += lambda stats: self._create_character(
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/__init__.py", line 196, in _create_character
    self._switch_to_game_view(player)
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/__init__.py", line 182, in _switch_to_game_view
    self._switch_view(view)
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/__init__.py", line 187, in _switch_view
    self._view.start()
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/views/game_view/__init__.py", line 197, in start
    self._plot_win = PlotWindow(
                     ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/views/game_view/plot_window.py", line 25, in __init__
    self.sync()
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/views/game_view/plot_window.py", line 46, in sync
    self._sync_position()
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/views/game_view/plot_window.py", line 69, in _sync_position
    self._render_progress_bar()
  File "/usr/lib/python3.12/site-packages/pqcli/ui/curses/views/game_view/progress_bar_window.py", line 68, in _render_progress_bar
    self._progress_bar_win.addnstr(
_curses.error: addnwstr() returned ERR
```

**Comment by rr-** [comment]
I believe this is fixed in 1.0.4 :)
