### ISSUE TITLE
random seed issue

### ISSUE THREAD

**Issue by Alveel** [rr-/pq-cli#24]
https://github.com/rr-/pq-cli/blob/9892b4c8f1cb7e1a09ef897b1851dcc903d7133c/pqcli/random.py#L5-L6

`random.seed()` already uses the current system time to generate a seed. This seems very double.

At least on my system (Python 3.11.8) when creating a character, I get the following error:

```
Traceback (most recent call last):
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/bin/pqcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/__main__.py", line 56, in main
    ui.run()
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/ui/curses/__init__.py", line 95, in run
    self._view.keypress(key)
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/ui/curses/views/create_character_view/choose_character_stats_view.py", line 58, in keypress
    self.on_confirm(self._stats)
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/ui/curses/event_handler.py", line 10, in __call__
    callback(*args, **kwargs)
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/ui/curses/__init__.py", line 145, in <lambda>
    view.on_confirm += lambda stats: self._create_character(
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/ui/curses/__init__.py", line 185, in _create_character
    player = create_player(name, race, class_, stats)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/mechanic.py", line 929, in create_player
    random.seed(now)
  File "/home/alwyn/.local/opt/pyenv/versions/progress-quest/lib/python3.11/site-packages/pqcli/random.py", line 6, in seed
    random.seed(source)
  File "/usr/lib/python3.11/random.py", line 160, in seed
    raise TypeError('The only supported seed types are: None,\n'
TypeError: The only supported seed types are: None,
int, float, str, bytes, and bytearray.
```

If I change the above code and remove the source parameter from `random.seed()` it works.

**Comment by rr-** [comment]
Fixed in `master`.
