### ISSUE TITLE
Ubuntu 18.04 Problems

### ISSUE THREAD

**Issue by Jaken58** [rr-/pq-cli#4]
Would you be willing to make this program a little easier to install on Ubuntu 18.04? I keep running into problems with it. 

It might just be that I don't have the required software needed, but I did install Python 3.7, and pip3 and follow the readme.md file.

**Comment by rr-** [comment]
@Jaken58 What errors do you get?

**Comment by Jaken58** [comment]
[From a clean install]
$ sudo apt-get install -y python-pip
$ python -m pip install --upgrade pip

[Error's]
pip install --user pq-cli
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by rr-** [comment]
Why do you install pip then update it by hand? Are you installing python 3?

**Comment by Jaken58** [comment]
I tried for both Python 2 and 3. For Python 3 I did the following.
$ sudo apt-get install -y python3 python3-pip
$ pip3 install --user pq-cli

[Errors]
Collecting pq-cli
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/pq-cli/

**Comment by rr-** [comment]
The instructions say to install `pqcli` not `pq-cli`.

>`pip install --user pqcli`
